"""Remove flagged_sections from AnalysisResult

Revision ID: 4356eba0249a
Revises: e9be8079a6ac
Create Date: 2026-02-07 17:48:02.684978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4356eba0249a'
down_revision: Union[str, Sequence[str], None] = 'e9be8079a6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'flagged_sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('flagged_sections', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
